repositories:
  - name: stakater
    url: https://stakater.github.io/stakater-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: longhorn
    url: https://charts.longhorn.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: cilium
    url: https://helm.cilium.io/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: rancher-latest
    url: https://releases.rancher.com/server-charts/latest
  - name: suse-edge
    url: https://suse-edge.github.io/charts
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: prometheus-operator-crds
    chart: prometheus-community/prometheus-operator-crds
    version: 20.0.0
    wait: true
    timeout: 30
  # - name: istio-base
  #   chart: istio/base
  #   namespace: istio-system
  #   values:
  #     - defaultRevision: default
  #   createNamespace: true
  #   wait: true
  # - name: istio-cni
  #   namespace: istio-system
  #   chart: istio/cni
  #   # needs:
  #   # - istio-system/istio-base
  #   wait: true
  # - name: istiod
  #   namespace: istio-system
  #   chart: istio/istiod
  #   needs:
  #     - istio-system/istio-cni
  #   wait: true
  #   # version: 1.17.0
  #   values:
  #     - pilot:
  #         cni:
  #           enabled: true
  #
  # - name: istio-ingressgateway
  #   namespace: istio-ingress
  #   chart: istio/gateway
  #   wait: true
  #   needs:
  #     - istio-system/istio-cni
  #   hooks:
  #     - events:
  #         - presync
  #       showlogs: true
  #       command: sh
  #       args:
  #         - -c
  #         - "kubectl create namespace istio-ingress --dry-run=client -o yaml | kubectl apply -f -"
  #     - events:
  #         - presync
  #       showlogs: true
  #       command: sh
  #       args:
  #         - -c
  #         - "kubectl label --dry-run=client -o yaml --overwrite namespace istio-ingress istio-injection=enabled | kubectl apply -f -"
  # version: 1.17.0

  # - name: cilium
  #   chart: cilium/cilium
  #   namespace: kube-system
  #   version: 1.16.5
  #   wait: true
  #   timeout: 120
  #   # reuseValues: true
  #   values:
  #     - kubeProxyReplacement: true
  #     # - k8sServiceHost: '{{ requiredEnv "IP_ADDRESS" }}'
  #     - k8sServiceHost: 127.0.0.1
  #     - k8sServicePort: 6443
  #     # - hostServices:
  #     #     enabled: true
  #     # - externalIPs:
  #     #     enabled: true
  #     # - nodePort:
  #     #     enabled: true
  #     # - hostPort:
  #     #     enabled: true
  #     # - bpf:
  #     #     masquerade: false
  #     - ipam:
  #         operator:
  #           clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
  #         # "10.1.0.0/16", "10.2.0.0/16"]
  #     - image:
  #         pullPolicy: IfNotPresent
  #     # - direct-routing-device: "ens18"
  #     # - devices:
  #     # - ens18
  #     # - ipam:
  #     #     mode: kubernetes
  #     # - ingressController:
  #     #     enabled: false
  #     #     default: true
  #     #     loadbalancerMode: shared
  #     # hostNetwork:
  #     #   enabled: true
  #     - operator:
  #         replicas: 1
  #     # - gatewayAPI:
  #     #   enabled: false
  #     # - l2announcements:
  #     #   enabled: false
  #     # - hubble:
  #     #     ui:
  #     #       enabled: true
  #     #     relay:
  #     #       enabled: true
  # # 17	   --set hubble.listenAddress=":4244" \
  # # 18	   --set hubble.relay.enabled=true \
  # # 19	   --set hubble.ui.enabled=true
  - name: reloader
    namespace: reloader
    chart: stakater/reloader
    version: 2.1.3
    wait: true
    timeout: 180
    # needs:
    #   - kube-system/cilium
    values:
      - reloader:
          watchGlobally: true
          autoReloadAll: true
          reloadOnCreate: true
          syncAfterRestart: true
          reloadStrategy: annotations
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.2
    wait: true
    timeout: 300
    # needs:
    #   - kube-system/cilium
    values:
      - crds:
          enabled: true
      - prometheus:
          enabled: false
  - name: cert-manager-issuers
    chart: incubator/raw
    version: 0.2.5
    wait: true
    timeout: 30
    needs:
      - cert-manager/cert-manager
    values:
      - resources:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: selfsigned
            spec:
              selfSigned: {}

  # - name: kubernetes-dashboard
  #   installed: false
  #   namespace: kubernetes-dashboard
  #   chart: kubernetes-dashboard/kubernetes-dashboard
  #   version: 7.10.1
  #   wait: true
  #   timeout: 180
  #   needs:
  #     - kube-system/cilium
  #   values:
  #     - app:
  #         ingress:
  #           enabled: true
  #           ingressClassName: traefik
  #           hosts:
  #             - dashboard.{{ requiredEnv "IP_ADDRESS" }}.sslip.io
  #           issuer:
  #             name: selfsigned
  #             scope: cluster
  #           tls:
  #             enabled: true
  #
  #     - metricsScraper:
  #         enabled: false
  # - name: dashboard-user
  #   chart: incubator/raw
  #   version: 0.1.0
  #   needs:
  #     - kubernetes-dashboard/kubernetes-dashboard
  #   values:
  #     - resources:
  #         - apiVersion: v1
  #           kind: ServiceAccount
  #           metadata:
  #             name: admin-user
  #             namespace: kubernetes-dashboard
  #         - apiVersion: rbac.authorization.k8s.io/v1
  #           kind: ClusterRoleBinding
  #           metadata:
  #             name: admin-user
  #           roleRef:
  #             apiGroup: rbac.authorization.k8s.io
  #             kind: ClusterRole
  #             name: cluster-admin
  #           subjects:
  #             - kind: ServiceAccount
  #               name: admin-user
  #               namespace: kubernetes-dashboard
  - name: rancher
    namespace: cattle-system
    chart: rancher-latest/rancher
    version: 2.11.1
    wait: true
    timeout: 600
    needs:
      # - kube-system/cilium
      - cert-manager/cert-manager
    values:
      - hostname: rancher.{{ requiredEnv "IP_ADDRESS" }}.sslip.io
      - replicas: 1

  - name: kubevirt-dashboard-extension
    namespace: cattle-ui-plugin-system
    chart: suse-edge/kubevirt-dashboard-extension
    version: 1.3.1
    wait: true
    timeout: 180
    needs:
      - cattle-system/rancher
    # values:
    #   - hostname: rancher.{{ requiredEnv "IP_ADDRESS" }}.sslip.io
    #   - replicas: 1
