FROM base/archlinux:2018.03.01

RUN pacman --noconfirm -Sy rofi
RUN pacman --noconfirm -Sy git
RUN pacman --noconfirm -Sy sudo vim nano


RUN echo -e '[archlinuxfr]\n\
SigLevel = Never\n\
Server = http://repo.archlinux.fr/$arch' >> /etc/pacman.conf


RUN pacman --noconfirm -Sy yaourt

RUN pacman --noconfirm -Sy filezilla


#  polybar remmina

# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    mkdir -p /etc/sudoers.d/ && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

USER developer
ENV HOME /home/developer


RUN yaourt --noconfirm -Sy base-devel
RUN yaourt --noconfirm -Sy aur/appimage-git

RUN cd ~; git clone https://github.com/RazZziel/PortableLinuxGames.git
RUN rm -f ~/PortableLinuxGames/AppImageAssistant.AppImage
RUN sudo ln -s $(which appimagetool) ~/PortableLinuxGames/AppImageAssistant.AppImage


ENV PATH=$PATH:~/PortableLinuxGames
