directory: ~/MyMusic/Music/                   # Where does the music live?
library: ~/MyMusic/musiclibrary.blb  # Where does the beets database live?
import:
    move: yes                              # Move your files to ~/Music/beets after import
plugins: lastgenre fetchart ftintitle smartplaylist random embedart # mpdupdate
embedart:
    auto: yes 

mpdupdate:
    host: localhost
    port: 6600 

smartplaylist:
    playlist_dir: ~/MyMusic/Playlists
    relative_to: ~/MyMusic/Playlists/
    auto: no
    playlists:
        - name: all.m3u
          query: ''                  # Matches all music in your library

        - name: languages/Russian.m3u8
          query: 'language:Russian'

        - name: artists/$artist.m3u8
          query: ''

        - name: genres/$genre.m3u8
          query: ''

        - name: playlists/metal/punk-goes-pop.m3u8
          query: 'album:punk goes pop'