directory: ~/MyMusic/Music/                   # Where does the music live?
library: ~/MyMusic/musiclibrary.blb  # Where does the beets database live?
import:
    move: yes                              # Move your files to ~/Music/beets after import
plugins: lastgenre fetchart ftintitle smartplaylist random embedart info duplicates # mpdupdate
embedart:
    auto: yes 

mpdupdate:
    host: localhost
    port: 6600 

smartplaylist:
    playlist_dir: ~/MyMusic/Playlists/dynamic/
    relative_to: ~/MyMusic/Playlists/dynamic/
    auto: no
    playlists:
        - name: all.m3u
          query: ''                  # Matches all music in your library

        - name: languages/$language.m3u8
          query: ''

        - name: artists/$artist.m3u8
          query: ''

        - name: genres/$genre.m3u8
          query: ''

        - name: playlists/metal/punk-goes-pop.m3u8
          query: ['album:"punk goes pop"', 'punkgoespop:1']

        - name: playlists/metal/melodical-death-metal.m3u8
          query:
            - 'genre:"melodic death metal"'

        - name: playlists/metal/metalcore.m3u8
          query:
            - 'genre:metalcore'
