#!/bin/bash


TMP_IMAGE=/tmp/i3_lock.png
rm $TMP_IMAGE 2>/dev/null

IMAGE=$(realpath $HOME/.wallpaper)

convert $IMAGE -resize 1920x1080^ -gravity center -extent 1920x1080 -sepia-tone 90% $TMP_IMAGE
text="Locked at $(date +'%a %d-%m-%Y %H:%M')"
convert $TMP_IMAGE  -font Arial -pointsize 13 \
          -draw "gravity south \
                 fill black  text 0,12 \"$text\" \
                 fill white  text 1,11 \"$text\" " ${TMP_IMAGE}


text="$(neofetch --off --stdout)"
convert $TMP_IMAGE  -font Arial -pointsize 13 \
         -draw "gravity NorthWest \
                fill black  text 12,12 \"$text\" \
                fill white  text 13,13 \"$text\" " ${TMP_IMAGE}


convert +append $TMP_IMAGE $TMP_IMAGE $TMP_IMAGE
