#!/bin/bash

source ~/.functions

IMAGE="$(realpath $HOME/.wallpaper)"
IMAGE2="$(realpath $HOME/.wallpaper2)"

if [ ! -f "$IMAGE" ]; then
  IMAGE="$(randomWallpaper)"
fi

if [ ! -f "$IMAGE2" ]; then
  IMAGE2="$(randomWallpaper)"
fi

TMP_IMAGE=/tmp/i3_lock.png

tmpfile=$(mktemp)
tmpfile2=$(mktemp)
function finish {
  rm -f "$tmpfile"
  rm -f "$tmpfile2"
}
trap finish EXIT

WALLPAPER_PATH="/tmp/lockscreen_$(basename "${IMAGE}")__$(basename "${IMAGE2}").png"

if [ ! -f "$WALLPAPER_PATH" ]; then
	echo "Converting..."
	time convert "$IMAGE" -resize 1920x1080^ -gravity center -extent 1920x1080 -set colorspace sRGB "$tmpfile"
    time convert "$IMAGE2" -resize 1920x1080^ -gravity center -extent 1920x1080 -set colorspace sRGB "$tmpfile2"
	time convert +append "$tmpfile" "$tmpfile2" "$WALLPAPER_PATH"
fi

getFont() {
  default_font="$2"
  font="$1"

  convert -list font | grep -q "Font: $font"
  font_exists=$?
  if [ $font_exists -ne 0 ]; then
    echo ${default_font}
  else
    echo $font
  fi
}

default_font="$(xrdb -query | grep normal_font | cut -f2 | sed -E 's/ /-/g')"
font=$(getFont "${default_font}" "FreeSans")
font=$(getFont "${default_font}" "Liberation-Sans")

default_monospace_font="$(xrdb -query | grep monospace_font | cut -f2 | sed -E 's/ /-/g')"
monospace_font=$(getFont "${default_monospace_font}" "fixed")
monospace_font=$(getFont "Hack-Regular-Nerd-Font-Complete-Mono" "$monospace_font")

echo "monospace font: $monospace_font"
echo "font: $font"

text="Locked at $(date +'%a %d-%m-%Y %H:%M')"
system_info="$(neofetch --off --stdout)"

time convert "$WALLPAPER_PATH"  -font $font -pointsize 13 \
        -draw "gravity SouthWest \
                 fill black  text 12,12 \"$text\" \
                 fill black  text 12,11 \"$text\" \
                 fill white  text 13,11 \"$text\" " \
	-draw "gravity NorthWest \
                fill black  text 12,14 \"$system_info\" \
                fill black  text 12,13 \"$system_info\" \
                fill white  text 13,13 \"$system_info\" " "${TMP_IMAGE}"

#time convert +append $TMP_IMAGE $TMP_IMAGE $TMP_IMAGE
